#!/bin/bash
set -euo pipefail

# realpath not availabe on Mac by default...
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}
ROOT_DIR="$(realpath $(dirname "$0")/..)"
ICLOUDDS_VERSION="$(cat pyproject.toml | grep version | cut -d'"' -f 2)"
echo "Current icloudds version: ${ICLOUDDS_VERSION}"

docker build \
  --progress auto \
  -t "gordonaspin/icloudds:${ICLOUDDS_VERSION}" \
  -f "Dockerfile" \
  "$ROOT_DIR"

docker tag "gordonaspin/icloudds:${ICLOUDDS_VERSION}" "gordonaspin/icloudds:${ICLOUDDS_VERSION}-alpine"
docker tag "gordonaspin/icloudds:${ICLOUDDS_VERSION}" "gordonaspin/icloudds:latest"
docker push -a gordonaspin/icloudds
