#!/bin/bash
set -euo pipefail

# realpath not availabe on Mac by default...
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}
ROOT_DIR="$(realpath $(dirname "$0")/..)"
ICLOUDDS_VERSION="$(cat pyproject.toml | grep version | cut -d'"' -f 2)"
REMOTE_HASH=$(git ls-remote https://github.com/gordonaspin/icloudds.git HEAD | awk '{ print $1 }')
echo "Current icloudds version: ${ICLOUDDS_VERSION}"
echo "Git remote hash: ${REMOTE_HASH}"

docker build \
  --build-arg CACHE_BUST=${REMOTE_HASH} \
  --progress plain \
  -t "gordonaspin/icloudds:${ICLOUDDS_VERSION}" \
  -f "Dockerfile" \
  "$ROOT_DIR"

docker tag "gordonaspin/icloudds:${ICLOUDDS_VERSION}" "gordonaspin/icloudds:${ICLOUDDS_VERSION}-alpine"
docker tag "gordonaspin/icloudds:${ICLOUDDS_VERSION}" "gordonaspin/icloudds:latest"
docker push -a gordonaspin/icloudds
