"""Constants"""
from enum import Enum, auto
# For retrying connection after timeouts and errors

AUTHENTICATION_MAX_RETRIES = 3
MAX_RETRIES = 3
DOWNLOAD_MEDIA_CHUNK_SIZE = 1024*1024
RETRY_SECONDS = 5
ICLOUD_CHECK_SECONDS = 20
ICLOUD_REFRESH_SECONDS = 90
UPLOAD_WORKERS = 1
DOWNLOAD_WORKERS = 32

class ExitCode(Enum):
    EXIT_NORMAL = 0
    EXIT_CLICK_EXCEPTION = 1
    EXIT_CLICK_USAGE = 2
    EXIT_FAILED_SEND_2SA_CODE = auto()
    EXIT_FAILED_VERIFY_2SA_CODE = auto()
    EXIT_FAILED_VERIFY_2FA_CODE = auto()
    EXIT_FAILED_MISSING_COMMAND = auto()
    EXIT_FAILED_LOGIN = auto()
    EXIT_FAILED_CLOUD_API = auto()
    EXIT_FAILED_2FA_REQUIRED  = auto()